// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

const SITE = 'https://www.allmetalbrake.com';
const LASTMOD = '2026-06-04';

// Per-page sitemap priorities / change frequencies, keyed by URL pathname
// (trailing-slash directory URLs).
const SITEMAP_META = {
  '/': { changefreq: 'weekly', priority: 1.0 },
  '/best-lists/': { changefreq: 'weekly', priority: 0.9 },
  '/guides/': { changefreq: 'weekly', priority: 0.9 },
  '/compare/': { changefreq: 'monthly', priority: 0.8 },
  '/about/': { changefreq: 'monthly', priority: 0.5 },
  '/contact/': { changefreq: 'yearly', priority: 0.4 },
  '/affiliate-disclosure/': { changefreq: 'yearly', priority: 0.3 },
  '/privacy/': { changefreq: 'yearly', priority: 0.3 },
  '/terms/': { changefreq: 'yearly', priority: 0.3 },
  '/best-asphalt-driveway-sealer-reviews/': { changefreq: 'monthly', priority: 0.9 },
  '/best-driveway-sealer/': { changefreq: 'monthly', priority: 0.9 },
  '/when-should-you-seal-a-new-asphalt-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/how-much-does-it-cost-to-seal-a-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-remove-moss-from-asphalt-driveway/': { changefreq: 'monthly', priority: 0.7 },
  '/how-to-seal-a-concrete-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-remove-oil-stains-from-driveway/': { changefreq: 'monthly', priority: 0.7 },
  '/how-long-for-driveway-sealer-to-dry/': { changefreq: 'monthly', priority: 0.7 },
  '/latex-ite-driveway-sealer-review/': { changefreq: 'monthly', priority: 0.8 },
  '/best-stamped-concrete-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-stain-concrete-patio-to-look-like-stone/': { changefreq: 'monthly', priority: 0.7 },
  '/best-deck-stain-reviews/': { changefreq: 'monthly', priority: 0.9 },
  '/best-deck-stain-for-pressure-treated-wood/': { changefreq: 'monthly', priority: 0.8 },
  '/best-redwood-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-garage-floor-epoxy/': { changefreq: 'monthly', priority: 0.9 },
  '/best-garage-floor-coating/': { changefreq: 'monthly', priority: 0.8 },
  '/best-basement-wall-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-cinder-block-sealer-reviews/': { changefreq: 'monthly', priority: 0.8 },
  '/best-granite-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-marble-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-polymeric-sand-for-pavers/': { changefreq: 'monthly', priority: 0.8 },
  '/best-water-based-paver-sealer-reviews/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-use-polymeric-sand/': { changefreq: 'monthly', priority: 0.7 },
  '/ryobi-tools-review/': { changefreq: 'monthly', priority: 0.8 },
  '/tekton-tools-review/': { changefreq: 'monthly', priority: 0.8 },
  '/milwaukee-vs-dewalt/': { changefreq: 'monthly', priority: 0.8 },
  '/reviews/grizzly-g0542-review/': { changefreq: 'monthly', priority: 0.8 },
  '/paver-sand-vs-play-sand/': { changefreq: 'monthly', priority: 0.9 },
  '/polymeric-sand-vs-regular-sand-for-pavers/': { changefreq: 'monthly', priority: 0.9 },
  '/polymeric-sand-alternatives/': { changefreq: 'monthly', priority: 0.7 },
  '/best-paver-sealer-natural-look/': { changefreq: 'monthly', priority: 0.9 },
  '/best-paver-sealers-for-a-wet-look/': { changefreq: 'monthly', priority: 0.8 },
  '/best-paver-sealer-for-pool-deck/': { changefreq: 'monthly', priority: 0.7 },
  '/asphalt-vs-concrete-driveway/': { changefreq: 'monthly', priority: 0.9 },
  '/how-to-fix-crumbling-asphalt-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/best-concrete-driveway-sealer-reviews/': { changefreq: 'monthly', priority: 0.9 },
  '/best-concrete-countertop-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-brick-sealer-reviews/': { changefreq: 'monthly', priority: 0.9 },
  '/best-stone-sealers-reviews/': { changefreq: 'monthly', priority: 0.8 },
  '/teak-oil-vs-teak-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-teak-sealer-reviews/': { changefreq: 'monthly', priority: 0.8 },
  '/best-water-based-polyurethane-for-floors/': { changefreq: 'monthly', priority: 0.7 },
  '/best-brush-for-water-based-polyurethane/': { changefreq: 'monthly', priority: 0.7 },
  '/spackle-vs-putty/': { changefreq: 'monthly', priority: 0.8 },
  '/barn-door-vs-french-door/': { changefreq: 'monthly', priority: 0.8 },
  '/best-hookaroon-reviews/': { changefreq: 'monthly', priority: 0.8 },
  '/rockwell-tools-review/': { changefreq: 'monthly', priority: 0.7 },
  '/rust-converter-vs-rust-remover/': { changefreq: 'monthly', priority: 0.6 },
  '/how-to-waterproof-basement-walls/': { changefreq: 'monthly', priority: 0.9 },
  '/best-exterior-wood-sealer/': { changefreq: 'monthly', priority: 0.9 },
  '/flex-seal-review/': { changefreq: 'monthly', priority: 0.8 },
  '/best-asphalt-crack-filler/': { changefreq: 'monthly', priority: 0.8 },
  '/best-deck-sealant/': { changefreq: 'monthly', priority: 0.9 },
  '/best-exterior-caulk/': { changefreq: 'monthly', priority: 0.9 },
  '/best-deck-paint/': { changefreq: 'monthly', priority: 0.9 },
  '/sealing-asphalt-driveway-pros-and-cons/': { changefreq: 'monthly', priority: 0.9 },
  '/best-home-generator-for-power-outages/': { changefreq: 'monthly', priority: 0.9 },
  '/best-self-propelled-lawn-mower/': { changefreq: 'monthly', priority: 0.9 },
  '/best-concrete-floor-paint/': { changefreq: 'monthly', priority: 0.9 },
  '/best-gutter-guards/': { changefreq: 'monthly', priority: 0.9 },
  '/best-driveway-cleaner/': { changefreq: 'monthly', priority: 0.9 },
  '/epoxy-garage-floor-cost/': { changefreq: 'monthly', priority: 0.8 },
  '/oil-based-vs-water-based-driveway-sealer/': { changefreq: 'monthly', priority: 0.9 },
  '/rain-after-sealing-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/what-temperature-to-seal-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/best-dehumidifier-for-basement/': { changefreq: 'monthly', priority: 0.9 },
  '/best-pressure-washer-surface-cleaner/': { changefreq: 'monthly', priority: 0.9 },
  '/best-luxury-vinyl-plank-flooring/': { changefreq: 'monthly', priority: 0.9 },
  '/best-stain-for-cedar-deck/': { changefreq: 'monthly', priority: 0.9 },
  '/best-lawn-weed-killer/': { changefreq: 'monthly', priority: 0.9 },
  '/how-to-seal-an-asphalt-driveway/': { changefreq: 'monthly', priority: 0.9 },
  '/how-often-to-seal-a-driveway/': { changefreq: 'monthly', priority: 0.9 },
  '/best-garage-floor-tiles/': { changefreq: 'monthly', priority: 0.9 },
  '/best-paint-for-ceilings/': { changefreq: 'monthly', priority: 0.9 },
  '/best-shop-vac-for-garage/': { changefreq: 'monthly', priority: 0.9 },
  '/best-zero-turn-mower-for-homeowners/': { changefreq: 'monthly', priority: 0.9 },
  '/polymeric-sand-pros-and-cons/': { changefreq: 'monthly', priority: 0.8 },
  '/coal-tar-vs-asphalt-emulsion-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/generac-generator-cost/': { changefreq: 'monthly', priority: 0.9 },
  '/how-to-caulk-exterior-windows/': { changefreq: 'monthly', priority: 0.8 },
  '/best-concrete-sealer/': { changefreq: 'monthly', priority: 0.9 },
  '/silane-vs-siloxane-sealer/': { changefreq: 'monthly', priority: 0.8 },
  '/best-ice-melt-for-concrete/': { changefreq: 'monthly', priority: 0.9 },
  '/best-fence-stain/': { changefreq: 'monthly', priority: 0.9 },
  '/deck-stain-drying-time/': { changefreq: 'monthly', priority: 0.8 },
  '/best-porch-paint/': { changefreq: 'monthly', priority: 0.9 },
  '/best-gas-water-heater/': { changefreq: 'monthly', priority: 0.9 },
  '/best-stud-finder/': { changefreq: 'monthly', priority: 0.9 },
  '/best-torque-wrench/': { changefreq: 'monthly', priority: 0.9 },
  '/best-string-trimmer/': { changefreq: 'monthly', priority: 0.9 },
  '/asphalt-driveway-resurfacing-cost/': { changefreq: 'monthly', priority: 0.9 },
  '/what-temperature-to-stain-a-deck/': { changefreq: 'monthly', priority: 0.8 },
  '/cost-to-seal-a-concrete-driveway/': { changefreq: 'monthly', priority: 0.8 },
  '/basement-waterproofing-cost/': { changefreq: 'monthly', priority: 0.9 },
  '/what-size-dehumidifier-for-basement/': { changefreq: 'monthly', priority: 0.8 },
  '/what-humidity-to-set-basement-dehumidifier/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-fix-a-damp-basement/': { changefreq: 'monthly', priority: 0.9 },
  '/how-long-does-caulk-take-to-dry/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-apply-garage-floor-epoxy/': { changefreq: 'monthly', priority: 0.9 },
  '/how-long-does-garage-floor-epoxy-take-to-cure/': { changefreq: 'monthly', priority: 0.8 },
  '/acid-etching-vs-grinding-garage-floor/': { changefreq: 'monthly', priority: 0.8 },
  '/which-shop-vac-filter/': { changefreq: 'monthly', priority: 0.7 },
  '/best-grout-sealer/': { changefreq: 'monthly', priority: 0.9 },
  '/best-driveway-paint/': { changefreq: 'monthly', priority: 0.9 },
  '/best-sump-pump/': { changefreq: 'monthly', priority: 0.9 },
  '/best-drain-snake/': { changefreq: 'monthly', priority: 0.9 },
  '/best-paint-sprayer/': { changefreq: 'monthly', priority: 0.9 },
  '/best-basement-floor-paint/': { changefreq: 'monthly', priority: 0.9 },
  '/best-paint-for-cinder-block/': { changefreq: 'monthly', priority: 0.9 },
  '/best-chimney-sealer/': { changefreq: 'monthly', priority: 0.9 },
  '/epoxy-vs-polyaspartic-garage-floor/': { changefreq: 'monthly', priority: 0.8 },
  '/epoxy-garage-floor-peeling/': { changefreq: 'monthly', priority: 0.8 },
  '/driveway-sealer-peeling/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-seal-pavers/': { changefreq: 'monthly', priority: 0.9 },
  '/paver-sealing-cost/': { changefreq: 'monthly', priority: 0.9 },
  '/how-often-to-seal-pavers/': { changefreq: 'monthly', priority: 0.8 },
  '/do-pavers-need-to-be-sealed/': { changefreq: 'monthly', priority: 0.8 },
  '/how-long-does-driveway-sealer-last/': { changefreq: 'monthly', priority: 0.8 },
  '/how-long-does-concrete-sealer-last/': { changefreq: 'monthly', priority: 0.8 },
  '/why-is-my-concrete-sealer-turning-white/': { changefreq: 'monthly', priority: 0.8 },
  '/best-concrete-crack-filler/': { changefreq: 'monthly', priority: 0.9 },
  '/solid-vs-semi-transparent-deck-stain/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-stain-a-deck/': { changefreq: 'monthly', priority: 0.9 },
  '/how-much-does-it-cost-to-stain-a-deck/': { changefreq: 'monthly', priority: 0.9 },
  '/deck-stain-peeling/': { changefreq: 'monthly', priority: 0.8 },
  '/how-to-strip-deck-stain/': { changefreq: 'monthly', priority: 0.9 },
  '/best-deck-cleaner/': { changefreq: 'monthly', priority: 0.9 },
  '/how-to-get-rid-of-mold-in-basement/': { changefreq: 'monthly', priority: 0.9 },
  '/efflorescence-on-basement-walls/': { changefreq: 'monthly', priority: 0.8 },
  '/interior-vs-exterior-basement-waterproofing/': { changefreq: 'monthly', priority: 0.8 },
};

// Redirects from the legacy `*.html` URLs to the new trailing-slash URLs,
// preserving link equity for already-indexed pages.
const REDIRECT_SLUGS = [
  'about', 'affiliate-disclosure', 'best-asphalt-driveway-sealer-reviews',
  'best-basement-wall-sealer', 'best-cinder-block-sealer-reviews',
  'best-deck-stain-for-pressure-treated-wood', 'best-deck-stain-reviews',
  'best-driveway-sealer', 'best-garage-floor-coating', 'best-garage-floor-epoxy',
  'best-granite-sealer', 'best-lists', 'best-marble-sealer', 'best-mens-back-shavers',
  'best-polymeric-sand-for-pavers', 'best-redwood-sealer', 'best-stamped-concrete-sealer',
  'best-water-based-paver-sealer-reviews', 'compare', 'contact', 'guides',
  'how-long-for-driveway-sealer-to-dry', 'how-much-does-it-cost-to-seal-a-driveway',
  'how-to-remove-moss-from-asphalt-driveway', 'how-to-remove-oil-stains-from-driveway',
  'how-to-seal-a-concrete-driveway', 'how-to-stain-concrete-patio-to-look-like-stone',
  'how-to-use-polymeric-sand', 'latex-ite-driveway-sealer-review', 'milwaukee-vs-dewalt',
  'privacy', 'reviews/grizzly-g0542-review', 'ryobi-tools-review', 'terms',
  'when-should-you-seal-a-new-asphalt-driveway',
  'paver-sand-vs-play-sand', 'polymeric-sand-vs-regular-sand-for-pavers',
  'polymeric-sand-alternatives', 'best-paver-sealer-natural-look',
  'best-paver-sealers-for-a-wet-look', 'best-paver-sealer-for-pool-deck',
  'asphalt-vs-concrete-driveway', 'how-to-fix-crumbling-asphalt-driveway',
  'best-concrete-driveway-sealer-reviews', 'best-concrete-countertop-sealer',
  'best-brick-sealer-reviews', 'best-stone-sealers-reviews',
  'teak-oil-vs-teak-sealer', 'best-teak-sealer-reviews',
  'best-water-based-polyurethane-for-floors',
  'best-brush-for-water-based-polyurethane', 'spackle-vs-putty',
  'barn-door-vs-french-door', 'best-hookaroon-reviews', 'rockwell-tools-review',
  'rust-converter-vs-rust-remover',
  'how-to-waterproof-basement-walls', 'best-exterior-wood-sealer',
  'flex-seal-review', 'best-asphalt-crack-filler',
  'best-deck-sealant',
  'best-exterior-caulk', 'best-deck-paint',
  'sealing-asphalt-driveway-pros-and-cons',
  'best-home-generator-for-power-outages', 'best-self-propelled-lawn-mower',
  'best-concrete-floor-paint', 'best-gutter-guards', 'best-driveway-cleaner',
  'epoxy-garage-floor-cost',
  'oil-based-vs-water-based-driveway-sealer',
  'rain-after-sealing-driveway',
  'what-temperature-to-seal-driveway',
  'best-dehumidifier-for-basement',
  'best-pressure-washer-surface-cleaner',
  'best-luxury-vinyl-plank-flooring',
  'best-stain-for-cedar-deck',
  'best-lawn-weed-killer',
  'how-to-seal-an-asphalt-driveway',
  'how-often-to-seal-a-driveway',
  'best-garage-floor-tiles',
  'best-paint-for-ceilings',
  'best-shop-vac-for-garage',
  'best-zero-turn-mower-for-homeowners',
  'polymeric-sand-pros-and-cons',
  'coal-tar-vs-asphalt-emulsion-sealer',
  'generac-generator-cost',
  'how-to-caulk-exterior-windows',
  'best-concrete-sealer',
  'silane-vs-siloxane-sealer',
  'best-ice-melt-for-concrete',
  'best-fence-stain',
  'deck-stain-drying-time',
  'best-porch-paint',
  'best-gas-water-heater',
  'best-stud-finder',
  'best-torque-wrench',
  'best-string-trimmer',
  'asphalt-driveway-resurfacing-cost',
  'what-temperature-to-stain-a-deck',
  'cost-to-seal-a-concrete-driveway',
  'basement-waterproofing-cost',
  'what-size-dehumidifier-for-basement',
  'what-humidity-to-set-basement-dehumidifier',
  'how-to-fix-a-damp-basement',
  'how-long-does-caulk-take-to-dry',
  'how-to-apply-garage-floor-epoxy',
  'how-long-does-garage-floor-epoxy-take-to-cure',
  'acid-etching-vs-grinding-garage-floor',
  'which-shop-vac-filter',
  'best-grout-sealer',
  'best-driveway-paint',
  'best-sump-pump',
  'best-drain-snake',
  'best-paint-sprayer',
  'best-basement-floor-paint',
  'best-paint-for-cinder-block',
  'best-chimney-sealer',
  'epoxy-vs-polyaspartic-garage-floor',
  'epoxy-garage-floor-peeling',
  'driveway-sealer-peeling',
  'how-to-seal-pavers',
  'paver-sealing-cost',
  'how-often-to-seal-pavers',
  'do-pavers-need-to-be-sealed',
  'how-long-does-driveway-sealer-last',
  'how-long-does-concrete-sealer-last',
  'why-is-my-concrete-sealer-turning-white',
  'best-concrete-crack-filler',
  'solid-vs-semi-transparent-deck-stain',
  'how-to-stain-a-deck',
  'how-much-does-it-cost-to-stain-a-deck',
  'deck-stain-peeling',
  'how-to-strip-deck-stain',
  'best-deck-cleaner',
  'how-to-get-rid-of-mold-in-basement',
  'efflorescence-on-basement-walls',
  'interior-vs-exterior-basement-waterproofing',
];

// Note: legacy `/index.html` already maps to the generated homepage file, so
// it needs no redirect.
const redirects = {};
for (const slug of REDIRECT_SLUGS) {
  redirects[`/${slug}.html`] = `/${slug}/`;
}

export default defineConfig({
  site: SITE,
  trailingSlash: 'always',
  build: {
    // Emit `about/index.html` so canonical URLs are trailing-slash directories.
    format: 'directory',
  },
  redirects,
  server: {
    port: 3000,
    host: true,
  },
  integrations: [
    sitemap({
      filter: (page) => !/\/(search|thank-you)\/?$/.test(new URL(page).pathname),
      serialize(item) {
        const url = new URL(item.url);
        const meta = SITEMAP_META[url.pathname];
        if (meta) {
          item.changefreq = meta.changefreq;
          item.priority = meta.priority;
        }
        item.lastmod = LASTMOD;
        return item;
      },
    }),
  ],
});
